# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the required OS
build:
  os: ubuntu-22.04

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: cEpiabm/docs/conf.py
