name: Functional tests (pyEpiabm)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: func test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64

      - name: install pyEpiabm
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pyEpiabm/.
      - name: run func tests
        run: |
          python pyEpiabm/run_tests.py --func
